/*-------------------------------------------------------------------------
 - mini.q - a minimalistic multiplayer fps
 - iso.cpp -> implements routines for iso surface
 -------------------------------------------------------------------------*/
#pragma once
#include "sys.hpp"
#include "csg.hpp"
#include "stl.hpp"
#include "math.hpp"

namespace q {
namespace iso {

// simple structure to describe meshes generated by marching cube or dual
// contouring
struct mesh {
  INLINE mesh(vec3f *pos=NULL, vec3f *nor=NULL, u32 *index=NULL, u32 vn=0, u32 idxn=0) :
    m_pos(pos), m_nor(nor), m_index(index), m_vertnum(vn), m_indexnum(idxn) {}
  ~mesh();
  vec3f *m_pos, *m_nor;
  u32 *m_index;
  u32 m_vertnum;
  u32 m_indexnum;
};

// tesselate along a grid the distance field with dual contouring algorithm
mesh dc_mesh(const vec3f &org, u32 cellnum, float cellsize, const csg::node &n);

// same but in multi-thread
mesh dc_mesh_mt(const vec3f &org, u32 cellnum, float cellsize, const csg::node &d);
void start();
void finish();
} /* namespace iso */
} /* namespace q */

