HEADERS=\
  con.hpp\
  game.hpp\
  iso.hpp\
  md2.hpp\
  net.hpp\
  ogl.hpp\
  physics.hpp\
  qef.hpp\
  renderer.hpp\
  script.hpp\
  shaders.hpp\
  sound.hpp\
  stl.hpp\
  sys.hpp\
  task.hpp\
  text.hpp

SHADER_DECLARATIONS=\
  data/shaders/debugunsplit_fp.decl\
  data/shaders/debugunsplit_vp.decl\
  data/shaders/fxaa_vp.decl\
  data/shaders/fxaa_fp.decl\
  data/shaders/deferred_fp.decl\
  data/shaders/deferred_vp.decl\
  data/shaders/split_deferred_fp.decl\
  data/shaders/split_deferred_vp.decl\
  data/shaders/simple_material_vp.decl\
  data/shaders/simple_material_fp.decl\
  data/shaders/forward_fp.decl\
  data/shaders/forward_vp.decl

con.o: con.cpp $(HEADERS)
csg.o: csg.cpp sys.hpp stl.hpp math.hpp csg.hpp
game.o: game.cpp $(HEADERS)
iso.o: iso.cpp iso.hpp csg.hpp math.hpp stl.hpp sys.hpp
md2.o: md2.cpp $(HEADERS)
mini.q.o: mini.q.cpp $(HEADERS)
net.o: net.cpp net.hpp stl.hpp sys.hpp
ogl.o: ogl.cpp ogl.hxx $(HEADERS)
qef.o: qef.cpp qef.hpp sys.hpp
physics.o: physics.cpp $(HEADERS)
renderer.o: renderer.cpp $(HEADERS) $(SHADER_DECLARATIONS)
shaders.o: shaders.cpp shaders.cxx $(HEADERS)
sound.o: sound.cpp $(HEADERS)
script.o: script.cpp $(HEADERS)
stl.o: stl.cpp math.hpp stl.hpp sys.hpp
sys.o: sys.cpp $(HEADERS)
task.o: task.cpp stl.hpp sys.hpp task.hpp
text.o: text.cpp font.hxx $(HEADERS)
ui.o: ui.cpp ogl.hpp sys.hpp stl.hpp math.hpp text.hpp ui.hpp

