BEGIN_SHADER(SHADERNAME)

#define UNIFORM(T,N) PUNIFORM(T,N,true)
#define UNIFORMI(T,N,X) PUNIFORMI(T,N,X,true)
#include VERTEX_PROGRAM
#undef UNIFORM
#undef UNIFORMI

#define UNIFORM(T,N) PUNIFORM(T,N,false)
#define UNIFORMI(T,N,X) PUNIFORMI(T,N,X,false)
#include FRAGMENT_PROGRAM
#undef UNIFORM
#undef UNIFORMI

END_SHADER(SHADERNAME)
#undef SHADERNAME
#undef VERTEX_PROGRAM
#undef FRAGMENT_PROGRAM

