GL_PROC(BlendColor, glBlendColor, PFNGLBLENDCOLORPROC)
GL_PROC(BlendEquation, glBlendEquation, PFNGLBLENDEQUATIONPROC)
GL_PROC(DrawRangeElements, glDrawRangeElements, PFNGLDRAWRANGEELEMENTSPROC)
GL_PROC(TexImage3D, glTexImage3D, PFNGLTEXIMAGE3DPROC)
GL_PROC(TexSubImage3D, glTexSubImage3D, PFNGLTEXSUBIMAGE3DPROC)
GL_PROC(CopyTexSubImage3D, glCopyTexSubImage3D, PFNGLCOPYTEXSUBIMAGE3DPROC)

